"""Project descriptor for hylaeanrover — the ONLY project-aware code.

Param schemas are generated by introspecting the real argparse parsers
(`build_parser()` in examples/train.py, evaluate.py, promote_model.py),
so adding a flag to a script makes it appear in the UI with no edits
here. Must run inside python/.venv where `maturin develop` installed
the native module.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import re
import sys
from functools import lru_cache
from typing import Any, Optional

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
PYTHON_DIR = os.path.join(REPO_ROOT, "python")
MODELS_DIR = os.path.join(REPO_ROOT, "models")
RUNS_DIR = os.path.join(PYTHON_DIR, "runs")

SCRIPTS = {
    "training": "examples/train.py",
    "eval": "examples/evaluate.py",
    "promote": "examples/promote_model.py",
}

# Params rendered inline on the node card; everything else folds into
# the "advanced" section. Purely presentational — the schema still
# carries every flag the script accepts.
COMMON_PARAMS = {
    "training": [
        "stage", "timesteps", "n_envs", "frame_skip", "seed",
        "max_steps", "save",
    ],
    "eval": ["stage", "episodes", "seed", "scenario", "max_steps", "deterministic"],
    "promote": ["stage", "run", "source", "frame_skip", "mission_supervisor"],
}

# Edge-resolved params: satisfied by connecting a parent node, never
# shown as editable fields.
INPUT_PARAMS = {
    "training": ["load", "vecnorm"],
    "eval": ["load", "vecnorm"],
    "promote": ["run"],
}

FILE_ROOTS = [("models", MODELS_DIR), ("runs", RUNS_DIR)]

# SB3 stdout table, e.g. "|    ep_rew_mean      | -12.3    |"
_METRIC_RE = re.compile(r"ep_rew_mean\s*\|\s*(-?[\d.eE+]+)")
_STEP_RE = re.compile(r"total_timesteps\s*\|\s*(\d+)")
_last_step: dict[int, int] = {}


def parse_metric_line(line: str) -> Optional[dict[str, Any]]:
    m = _STEP_RE.search(line)
    if m:
        _last_step[0] = int(m.group(1))
        return None
    m = _METRIC_RE.search(line)
    if m:
        return {"ep_rew_mean": float(m.group(1)), "step": _last_step.get(0)}
    return None


def _load_script_module(rel_path: str):
    path = os.path.join(PYTHON_DIR, rel_path)
    name = "rl_studio_" + os.path.splitext(os.path.basename(rel_path))[0]
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def _action_to_param(a: argparse.Action) -> Optional[dict[str, Any]]:
    if not a.option_strings or isinstance(a, argparse._HelpAction):
        return None
    if isinstance(a, (argparse._StoreTrueAction, argparse._StoreFalseAction)):
        ptype = "flag"
    elif a.type is int:
        ptype = "int"
    elif a.type is float:
        ptype = "float"
    else:
        ptype = "str"
    default = a.default
    if default is not None and not isinstance(default, (int, float, str, bool)):
        default = str(default)
    return {
        "name": a.dest,
        "flag": max(a.option_strings, key=len),
        "type": ptype,
        "default": default,
        "choices": [str(c) for c in a.choices] if a.choices is not None else None,
        "required": bool(a.required),
        "help": a.help or "",
    }


@lru_cache(maxsize=None)
def _params_for(node_type: str) -> list[dict[str, Any]]:
    mod = _load_script_module(SCRIPTS[node_type])
    params = []
    for a in mod.build_parser()._actions:
        p = _action_to_param(a)
        if p is not None:
            p["common"] = p["name"] in COMMON_PARAMS.get(node_type, [])
            p["is_input"] = p["name"] in INPUT_PARAMS.get(node_type, [])
            params.append(p)
    return params


def describe() -> dict[str, Any]:
    try:
        from hylaeanrover.wrappers import STAGES
        from hylaeanrover._native import RoverEnv as _Native

        return {
            "ok": True,
            "stages": list(STAGES),
            "obs_dim": _Native.obs_dim(),
            "n_actions": _Native.action_count(),
        }
    except Exception as exc:  # stale/missing native build
        return {
            "ok": False,
            "error": f"{type(exc).__name__}: {exc}",
            "hint": "run `maturin develop --release` in python/ with .venv active",
            "stages": [],
            "obs_dim": None,
            "n_actions": None,
        }


def node_types() -> dict[str, dict[str, Any]]:
    return {
        "training": {
            "title": "Train",
            "script": SCRIPTS["training"],
            "params": _params_for("training"),
            "outputs": ["model.zip", "vecnorm.pkl"],
            "accepts_input": True,
        },
        "eval": {
            "title": "Evaluate",
            "script": SCRIPTS["eval"],
            "params": _params_for("eval"),
            "outputs": [],
            "accepts_input": True,
        },
        "promote": {
            "title": "Promote",
            "script": SCRIPTS["promote"],
            "params": _params_for("promote"),
            "outputs": ["model.zip", "vecnorm.pkl", "model.onnx", "model.norm.json"],
            "accepts_input": True,
        },
        "artifact": {
            "title": "Model artifact",
            "params": [],
            "outputs": ["bundle"],
            "accepts_input": False,
        },
    }


# --- Bundle / input resolution -----------------------------------------

def output_dir(node: dict[str, Any]) -> Optional[str]:
    """Absolute dir where a node's output bundle lives (or will live)."""
    t = node["type"]
    params = node.get("params", {})
    if t == "artifact":
        p = node.get("path")
        if p and not os.path.isabs(p):
            p = os.path.join(REPO_ROOT, p)
        return p
    if t == "training":
        save = params.get("save")
        return os.path.join(PYTHON_DIR, save) if save else None
    if t == "promote":
        stage = params.get("stage")
        return os.path.join(MODELS_DIR, stage) if stage else None
    return None


def _bundle_paths(d: str) -> Optional[dict[str, str]]:
    model = os.path.join(d, "model.zip")
    if not os.path.exists(model):
        return None
    out = {"load": model}
    vecnorm = os.path.join(d, "vecnorm.pkl")
    if os.path.exists(vecnorm):
        out["vecnorm"] = vecnorm
    return out


def resolve_inputs(
    node: dict[str, Any], parents: list[dict[str, Any]]
) -> dict[str, Any]:
    """Map parent output bundles onto this node's input params."""
    if not parents:
        return {}
    parent_dir = output_dir(parents[0])
    if parent_dir is None:
        raise ValueError(
            f"parent node {parents[0]['id']!r} has no resolvable output dir"
        )
    t = node["type"]
    if t == "promote":
        # promote consumes the run dir itself, not a model.zip
        return {"run": parent_dir}
    if t in ("training", "eval"):
        bundle = _bundle_paths(parent_dir)
        if bundle is None:
            raise ValueError(
                f"no model.zip in {parent_dir} — has the parent node finished?"
            )
        return bundle
    return {}


def find_onnx(node: dict[str, Any]) -> Optional[str]:
    """A launchable .onnx reachable from this node, if any."""
    d = output_dir(node)
    if d:
        p = os.path.join(d, "model.onnx")
        if os.path.exists(p):
            return p
    return None


# --- argv builders ------------------------------------------------------

def build_argv(
    node_type: str, params: dict[str, Any], inputs: dict[str, Any]
) -> tuple[list[str], str]:
    """Return (argv, cwd) for a script node."""
    schema = {p["name"]: p for p in _params_for(node_type)}
    argv = [sys.executable, SCRIPTS[node_type]]
    merged = {**params, **inputs}  # edge-resolved inputs win
    for name, value in merged.items():
        spec = schema.get(name)
        if spec is None or value is None or value == "":
            continue
        if spec["type"] == "flag":
            if value in (True, "true", "True", 1):
                argv.append(spec["flag"])
        else:
            argv.append(spec["flag"])
            argv.append(str(value))
    return argv, PYTHON_DIR


def build_sim_argv(onnx_path: str) -> tuple[list[str], str]:
    return (
        [
            "cargo", "run", "-p", "hylaeanrover_game", "--release", "--",
            "--policy", onnx_path,
        ],
        REPO_ROOT,
    )
